Update dev-lambda-deploy.yml

diff --git a/.github/workflows/dev-lambda-deploy.yml b/.github/workflows/dev-lambda-deploy.yml
--- a/.github/workflows/dev-lambda-deploy.yml
+++ b/.github/workflows/dev-lambda-deploy.yml
@@ -15,7 +15,7 @@ jobs:
       - name: Simulate successful deployment
         run: |
           echo "Deployment succeeded"
-      - name: Simulate failed deployment
-        run: |
-          echo "Simulating failure..."
-          exit 1  # Fail the job
+      # - name: Simulate failed deployment
+      #   run: |
+      #     echo "Simulating failure..."
+      #     exit 1  # Fail the job
